[package]
name = "fd"
version = "0.1.0"
authors = ["Mickaël Salaün <mic@digikod.net>"]
description = "File descriptor utilities"
repository = "https://github.com/stemjail/fd-rs"
readme = "README.md"
keywords = ["linux", "fd", "splice", "pipe"]
license = "LGPL-3.0"
exclude = [".gitignore"]
